import type { CategoryConfig } from '../../src/types/preferences';

export const clothingConfig: CategoryConfig = {
  id: 'clothing',
  label: 'Clothing',
  keywords: [
    'shirt',
    't-shirt',
    'tshirt',
    'kurta',
    'kurti',
    'dress',
    'jeans',
    'trouser',
    'pant',
    'pants',
    'saree',
    'sari',
    'lehenga',
    'top',
    'blouse',
    'hoodie',
    'sweater',
    'jacket',
    'coat',
    'shorts',
    'skirt',
    'ethnic',
    'western',
    'formal',
    'casual',
    'clothing',
    'clothes',
    'apparel',
    'wear',
  ],
  subcategories: {
    topwear: ['shirt', 't-shirt', 'tshirt', 'kurta', 'kurti', 'top', 'blouse', 'hoodie', 'sweater'],
    bottomwear: ['jeans', 'trouser', 'pant', 'pants', 'shorts', 'skirt'],
    dresswear: ['dress', 'saree', 'sari', 'lehenga', 'gown'],
    outerwear: ['jacket', 'coat'],
  },
  required: ['budget'],
  conditional: [
    {
      when: { subcategory: ['shirt', 't-shirt', 'tshirt', 'kurta', 'kurti', 'top', 'blouse', 'hoodie'] },
      fields: ['size', 'fit'],
    },
    {
      when: { subcategory: ['jeans', 'trouser', 'pant', 'pants', 'shorts'] },
      fields: ['size', 'fit'],
    },
    {
      when: { subcategory: ['dress', 'saree', 'sari', 'lehenga', 'gown'] },
      fields: ['size', 'fabric'],
    },
    {
      when: { subcategory: ['sweater', 'jacket', 'coat'] },
      fields: ['size'],
    },
  ],
  optional: ['color', 'fabric', 'sleeveless', 'gender'],
  optionalImpact: {
    color: 0.9,
    fabric: 0.85,
    sleeveless: 0.6,
    gender: 0.7,
  },
  maxQuestions: 5,
  fields: {
    size: {
      type: 'checkbox',
      label: 'Size',
      options: [
        { value: 'XS', label: 'XS' },
        { value: 'S', label: 'S' },
        { value: 'M', label: 'M' },
        { value: 'L', label: 'L' },
        { value: 'XL', label: 'XL' },
        { value: 'XXL', label: 'XXL' },
      ],
      multi: false,
    },
    color: {
      type: 'checkbox',
      label: 'Color',
      options: [
        { value: 'black', label: 'Black' },
        { value: 'white', label: 'White' },
        { value: 'blue', label: 'Blue' },
        { value: 'red', label: 'Red' },
        { value: 'green', label: 'Green' },
        { value: 'pink', label: 'Pink' },
        { value: 'beige', label: 'Beige / Neutral' },
        { value: 'multicolor', label: 'Multicolor' },
      ],
      multi: true,
    },
    fit: {
      type: 'checkbox',
      label: 'Fit',
      options: [
        { value: 'slim', label: 'Slim' },
        { value: 'regular', label: 'Regular' },
        { value: 'relaxed', label: 'Relaxed' },
        { value: 'oversized', label: 'Oversized' },
      ],
      multi: false,
    },
    budget: {
      type: 'range',
      label: 'Budget',
      min: 299,
      max: 15_000,
      step: 100,
      currency: 'INR',
      presets: [
        { label: 'Under ₹500', min: 299, max: 500 },
        { label: '₹500 – ₹1,500', min: 500, max: 1_500 },
        { label: '₹1,500 – ₹3,000', min: 1_500, max: 3_000 },
        { label: '₹3,000+', min: 3_000, max: 15_000 },
      ],
    },
    fabric: {
      type: 'checkbox',
      label: 'Fabric',
      options: [
        { value: 'cotton', label: 'Cotton' },
        { value: 'linen', label: 'Linen' },
        { value: 'polyester', label: 'Polyester' },
        { value: 'blend', label: 'Blend' },
        { value: 'silk', label: 'Silk' },
        { value: 'denim', label: 'Denim' },
        { value: 'wool', label: 'Wool' },
      ],
      multi: true,
    },
    sleeveless: {
      type: 'checkbox',
      label: 'Sleeveless',
      options: [
        { value: 'yes', label: 'Yes' },
        { value: 'no', label: 'No' },
      ],
      multi: false,
    },
    gender: {
      type: 'checkbox',
      label: 'For',
      options: [
        { value: 'men', label: 'Men' },
        { value: 'women', label: 'Women' },
        { value: 'unisex', label: 'Unisex' },
      ],
      multi: false,
    },
  },
};